---
services:
  scantrack-node:
    build:
      context: .
      dockerfile: ScanTrackNode/Dockerfile
    container_name: scantrack-node
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      CITY_NAME: Kiruna
      NODE_URL: http://localhost:8080
      REGISTRY_URL: http://scantrack-registry-iths.northeurope.azurecontainer.io:8080
